In [1]:
#Sort, Search and COunting Functions

In [2]:
import numpy as np

In [4]:
arr = np.array([4,3,2,1,5,6,7,8,9,10])

In [5]:
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.searchsorted(arr,12)

10

In [8]:
arr1 = np.array([0,344,222,1,0,4,4,0,0,0,0])

In [10]:
np.count_nonzero(arr1)

5

In [11]:
arr

array([ 4,  3,  2,  1,  5,  6,  7,  8,  9, 10])

In [12]:
np.where(arr < 5)

(array([0, 1, 2, 3], dtype=int64),)

In [13]:
np.where(arr >4)

(array([4, 5, 6, 7, 8, 9], dtype=int64),)

In [14]:
np.extract(arr<5,arr)

array([4, 3, 2, 1])

In [15]:
#Byte Swapping

In [16]:
arr

array([ 4,  3,  2,  1,  5,  6,  7,  8,  9, 10])

In [17]:
arr.byteswap()

array([ 67108864,  50331648,  33554432,  16777216,  83886080, 100663296,
       117440512, 134217728, 150994944, 167772160])

In [18]:
#Copies and Views

In [20]:
a = np.copy(arr) #Deep Copy

In [21]:
b = arr.view() #Shallow Copy

In [30]:
b = arr 

In [24]:
b

array([ 4,  3,  2,  1,  5,  6,  7,  8,  9, 10])

In [25]:
arr

array([ 4,  3,  2,  1,  5,  6,  7,  8,  9, 10])

In [26]:
b[0] = 100

In [27]:
b

array([100,   3,   2,   1,   5,   6,   7,   8,   9,  10])

In [28]:
arr

array([100,   3,   2,   1,   5,   6,   7,   8,   9,  10])

In [31]:
#Matrix Library

In [32]:
import numpy.matlib as nm

In [34]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [35]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [36]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [37]:
#Linear Algebra

In [38]:
arr1 = np.array([[1,2],[3,4]])

In [39]:
arr2 = np.array([[5,6],[7,8]])

In [40]:
np.dot(arr1,arr2)

array([[19, 22],
       [43, 50]])

In [41]:
arr1@arr2

array([[19, 22],
       [43, 50]])