In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [4]:
ar = np.array(l)

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray(l)

array([1, 2, 3, 4])

In [8]:
a = [2,3,4]

In [9]:
np.asanyarray(a)

array([2, 3, 4])

In [10]:
b = np.matrix(l)

In [11]:
b

matrix([[1, 2, 3, 4]])

In [12]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [13]:
a = np.array(l)

In [15]:
c = a

In [16]:
c

array([1, 2, 3, 4])

In [17]:
a

array([1, 2, 3, 4])

In [18]:
c[0]

1

In [19]:
c[0] = 100

In [20]:
c

array([100,   2,   3,   4])

In [21]:
a

array([100,   2,   3,   4])

In [22]:
d = np.copy(a)

In [23]:
d

array([100,   2,   3,   4])

In [24]:
a

array([100,   2,   3,   4])

In [27]:
a[1] = 400

In [28]:
a

array([100, 400,   3,   4])

In [29]:
d

array([100,   2,   3,   4])

In [30]:
#swallow copy and deep copy

In [32]:
np.fromfunction(lambda i,j : i == j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [33]:
np.fromfunction(lambda i,j : i * j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [34]:
iterable = ( i*i for i in range(5))

In [36]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [37]:
np.fromstring('234 234',sep = ' ')

array([234., 234.])

In [38]:
np.fromstring('4,5',sep = ',')

array([4., 5.])

In [39]:
# Numpy Data Types

In [40]:
l = [2,3,4,5,6]

In [42]:
ar = np.array(l)

In [43]:
ar

array([2, 3, 4, 5, 6])

In [44]:
ar.ndim

1

In [45]:
ar2 = np.array([[1,2,3,4],[3,4,5,6]])

In [46]:
ar2.ndim

2

In [47]:
ar.size

5

In [48]:
ar2.size

8

In [49]:
ar

array([2, 3, 4, 5, 6])

In [50]:
ar2

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [51]:
ar.shape

(5,)

In [52]:
ar2.shape

(2, 4)

In [53]:
ar.dtype

dtype('int32')

In [54]:
ar2.dtype

dtype('int32')

In [56]:
ar22 = np.array([(1.4,45,45),(23,45,66)])

In [57]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [58]:
ar22.dtype

dtype('float64')

In [60]:
list(range(5))

[0, 1, 2, 3, 4]

In [61]:
list(range(0.1,5))

TypeError: 'float' object cannot be interpreted as an integer

In [64]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [66]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [67]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [68]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [69]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [72]:
ar4 = np.zeros((3,4,2,3))

In [74]:
ar4.ndim

4

In [75]:
np.ones(4)

array([1., 1., 1., 1.])

In [76]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [78]:
on = np.ones((2,3,2))

In [79]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [80]:
on * 4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [88]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [89]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [91]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [92]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [93]:
np.logspace(2,5,10,base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [96]:
arr = np.random.randn(3,4)

In [97]:
import pandas as pd

In [98]:
pd.DataFrame(arr)

0         1         2         3
0  0.525053  0.486832  0.112692 -1.319575
1  1.043508 -1.046896  1.023873  0.052595
2  0.852488  1.035019  0.056469 -0.297526

In [99]:
np.random.rand(3,4)

array([[0.30001448, 0.77844705, 0.90758211, 0.01250211],
       [0.65242116, 0.47028986, 0.50786659, 0.77011409],
       [0.81107919, 0.60208767, 0.90623773, 0.06177609]])

In [100]:
np.random.randint(1,110,(3,4))

array([[ 86, 104,   8,  50],
       [ 25,  62,  37,  83],
       [ 85,  46,  50,  51]])

In [103]:
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv('test.csv')

In [104]:
arr = np.random.rand(3,4)

In [105]:
arr

array([[0.1609069 , 0.33203602, 0.10520162, 0.38042541],
       [0.4131888 , 0.08907842, 0.39210016, 0.56709387],
       [0.46944721, 0.67489466, 0.45768866, 0.02175693]])

In [106]:
arr.reshape(6,2)

array([[0.1609069 , 0.33203602],
       [0.10520162, 0.38042541],
       [0.4131888 , 0.08907842],
       [0.39210016, 0.56709387],
       [0.46944721, 0.67489466],
       [0.45768866, 0.02175693]])

In [109]:
arr1 = arr.reshape(6,-11393993)

In [110]:
arr1[1][1]

0.38042540897541866

In [113]:
arr1[2:5,1]

array([0.08907842, 0.56709387, 0.67489466])

In [115]:
arr = np.random.randint(1,100,(5,5))

In [116]:
arr

array([[10, 39, 55, 44, 12],
       [ 6, 54, 66, 77, 13],
       [66, 71, 86, 12, 86],
       [23,  7, 48, 43, 60],
       [50,  5, 91, 73, 54]])

In [117]:
arr > 50

array([[False, False,  True, False, False],
       [False,  True,  True,  True, False],
       [ True,  True,  True, False,  True],
       [False, False, False, False,  True],
       [False, False,  True,  True,  True]])

In [118]:
arr[arr>50]

array([55, 54, 66, 77, 66, 71, 86, 86, 60, 91, 73, 54])

In [119]:
arr

array([[10, 39, 55, 44, 12],
       [ 6, 54, 66, 77, 13],
       [66, 71, 86, 12, 86],
       [23,  7, 48, 43, 60],
       [50,  5, 91, 73, 54]])

In [120]:
arr[2:4,[1,2]]

array([[71, 86],
       [ 7, 48]])

In [121]:
arr[0][0]

10

In [122]:
arr[0][0] = 500

In [123]:
arr

array([[500,  39,  55,  44,  12],
       [  6,  54,  66,  77,  13],
       [ 66,  71,  86,  12,  86],
       [ 23,   7,  48,  43,  60],
       [ 50,   5,  91,  73,  54]])

In [124]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [125]:
arr1    

array([[2, 2, 1],
       [1, 2, 2],
       [1, 2, 2]])

In [126]:
arr2

array([[1, 1, 2],
       [2, 1, 2],
       [1, 2, 1]])

In [127]:
arr1 + arr2

array([[3, 3, 3],
       [3, 3, 4],
       [2, 4, 3]])

In [128]:
arr1 - arr2

array([[ 1,  1, -1],
       [-1,  1,  0],
       [ 0,  0,  1]])

In [129]:
arr1/arr2

array([[2. , 2. , 0.5],
       [0.5, 2. , 1. ],
       [1. , 1. , 2. ]])

In [130]:
arr1 * arr2

array([[2, 2, 2],
       [2, 2, 4],
       [1, 4, 2]])

In [131]:
arr1

array([[2, 2, 1],
       [1, 2, 2],
       [1, 2, 2]])

In [132]:
arr2

array([[1, 1, 2],
       [2, 1, 2],
       [1, 2, 1]])

In [133]:
arr1@arr2

array([[7, 6, 9],
       [7, 7, 8],
       [7, 7, 8]])

In [134]:
arr1/0

C:\Users\Hp\AppData\Local\Temp\ipykernel_12244\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [135]:
arr1 + 100

array([[102, 102, 101],
       [101, 102, 102],
       [101, 102, 102]])

In [136]:
arr1 ** 2

array([[4, 4, 1],
       [1, 4, 4],
       [1, 4, 4]])

In [137]:
# Broadcasting

In [139]:
arr = np.zeros((4,4))

In [140]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [141]:
row = np.array([1,2,3,4])

In [142]:
row

array([1, 2, 3, 4])

In [143]:
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [144]:
row.T

array([1, 2, 3, 4])

In [145]:
col = np.array([[1,2,3,4]])

In [146]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [147]:
col

array([[1, 2, 3, 4]])

In [148]:
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [149]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [151]:
arr1 = np.random.randint(1,4,(3,4))

In [152]:
arr1

array([[2, 3, 2, 1],
       [3, 1, 1, 1],
       [2, 2, 2, 3]])

In [153]:
np.sqrt(arr1)

array([[1.41421356, 1.73205081, 1.41421356, 1.        ],
       [1.73205081, 1.        , 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.41421356, 1.73205081]])

In [154]:
np.exp(arr1)

array([[ 7.3890561 , 20.08553692,  7.3890561 ,  2.71828183],
       [20.08553692,  2.71828183,  2.71828183,  2.71828183],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 , 20.08553692]])

In [155]:
np.exp(arr1)

array([[ 7.3890561 , 20.08553692,  7.3890561 ,  2.71828183],
       [20.08553692,  2.71828183,  2.71828183,  2.71828183],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 , 20.08553692]])

In [156]:
np.log10(arr1)

array([[0.30103   , 0.47712125, 0.30103   , 0.        ],
       [0.47712125, 0.        , 0.        , 0.        ],
       [0.30103   , 0.30103   , 0.30103   , 0.47712125]])