In [1]:
#Numpy Array Manipulation

In [2]:
import numpy as np

In [6]:
arr = np.random.randint(1,10,(3,4))

In [7]:
arr

array([[1, 6, 6, 4],
       [1, 1, 4, 7],
       [8, 2, 8, 2]])

In [8]:
arr.reshape(6,2)

array([[1, 6],
       [6, 4],
       [1, 1],
       [4, 7],
       [8, 2],
       [8, 2]])

In [10]:
arr.reshape(2,6)

array([[1, 6, 6, 4, 1, 1],
       [4, 7, 8, 2, 8, 2]])

In [11]:
arr.reshape(2,-13939933)

array([[1, 6, 6, 4, 1, 1],
       [4, 7, 8, 2, 8, 2]])

In [12]:
arr.T

array([[1, 1, 8],
       [6, 1, 2],
       [6, 4, 8],
       [4, 7, 2]])

In [13]:
arr

array([[1, 6, 6, 4],
       [1, 1, 4, 7],
       [8, 2, 8, 2]])

In [14]:
arr.flatten()

array([1, 6, 6, 4, 1, 1, 4, 7, 8, 2, 8, 2])

In [15]:
arr1 = np.array([1,2,3,3,4])

In [17]:
arr1.ndim

1

In [18]:
np.expand_dims(arr1,axis = 1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [19]:
np.expand_dims(arr1,axis = 0)

array([[1, 2, 3, 3, 4]])

In [20]:
arr

array([[1, 6, 6, 4],
       [1, 1, 4, 7],
       [8, 2, 8, 2]])

In [21]:
np.squeeze(arr)

array([[1, 6, 6, 4],
       [1, 1, 4, 7],
       [8, 2, 8, 2]])

In [22]:
data = np.array([[1],[2],[3]])

In [23]:
data

array([[1],
       [2],
       [3]])

In [24]:
np.squeeze(data)

array([1, 2, 3])

In [25]:
arr1

array([1, 2, 3, 3, 4])

In [26]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [27]:
np.roll(arr1,2)

array([3, 4, 1, 2, 3])

In [28]:
arr1

array([1, 2, 3, 3, 4])

In [29]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [30]:
#Binary Operators

In [31]:
arr1 = np.random.randint(1,10,(3,4))

In [32]:
arr2 = np.random.randint(1,10,(3,4))

In [33]:
arr1

array([[3, 6, 4, 7],
       [4, 3, 9, 1],
       [9, 1, 1, 5]])

In [34]:
arr2

array([[4, 9, 8, 7],
       [3, 9, 8, 4],
       [8, 6, 8, 9]])

In [35]:
arr1 + arr2

array([[ 7, 15, 12, 14],
       [ 7, 12, 17,  5],
       [17,  7,  9, 14]])

In [36]:
arr1 * arr2

array([[12, 54, 32, 49],
       [12, 27, 72,  4],
       [72,  6,  8, 45]])

In [37]:
arr1 / arr2

array([[0.75      , 0.66666667, 0.5       , 1.        ],
       [1.33333333, 0.33333333, 1.125     , 0.25      ],
       [1.125     , 0.16666667, 0.125     , 0.55555556]])

In [38]:
arr1 - arr2

array([[-1, -3, -4,  0],
       [ 1, -6,  1, -3],
       [ 1, -5, -7, -4]])

In [39]:
arr1 % arr2

array([[3, 6, 4, 0],
       [1, 3, 1, 1],
       [1, 1, 1, 5]])

In [41]:
arr1 ** arr2

array([[      81, 10077696,    65536,   823543],
       [      64,    19683, 43046721,        1],
       [43046721,        1,        1,  1953125]])

In [42]:
arr1 & arr2

array([[0, 0, 0, 7],
       [0, 1, 8, 0],
       [8, 0, 0, 1]])

In [43]:
arr1

array([[3, 6, 4, 7],
       [4, 3, 9, 1],
       [9, 1, 1, 5]])

In [45]:
arr2

array([[4, 9, 8, 7],
       [3, 9, 8, 4],
       [8, 6, 8, 9]])

In [46]:
~arr1

array([[ -4,  -7,  -5,  -8],
       [ -5,  -4, -10,  -2],
       [-10,  -2,  -2,  -6]])

In [47]:
arr1 | arr2

array([[ 7, 15, 12,  7],
       [ 7, 11,  9,  5],
       [ 9,  7,  9, 13]])

In [48]:
arr1 > arr2

array([[False, False, False, False],
       [ True, False,  True, False],
       [ True, False, False, False]])

In [49]:
#String Functions

In [51]:
arr = np.array(['nabin','katwal'])

In [52]:
np.char.upper(arr)

array(['NABIN', 'KATWAL'], dtype='<U6')

In [53]:
np.char.title(arr)

array(['Nabin', 'Katwal'], dtype='<U6')

In [54]:
np.char.capitalize(arr)

array(['Nabin', 'Katwal'], dtype='<U6')

In [56]:
#Mathematical Functions

In [57]:
arr1

array([[3, 6, 4, 7],
       [4, 3, 9, 1],
       [9, 1, 1, 5]])

In [58]:
np.sin(arr1)

array([[ 0.14112001, -0.2794155 , -0.7568025 ,  0.6569866 ],
       [-0.7568025 ,  0.14112001,  0.41211849,  0.84147098],
       [ 0.41211849,  0.84147098,  0.84147098, -0.95892427]])

In [59]:
np.cos(arr1)

array([[-0.9899925 ,  0.96017029, -0.65364362,  0.75390225],
       [-0.65364362, -0.9899925 , -0.91113026,  0.54030231],
       [-0.91113026,  0.54030231,  0.54030231,  0.28366219]])

In [60]:
np.tan(arr1)

array([[-0.14254654, -0.29100619,  1.15782128,  0.87144798],
       [ 1.15782128, -0.14254654, -0.45231566,  1.55740772],
       [-0.45231566,  1.55740772,  1.55740772, -3.38051501]])

In [61]:
np.tanh(arr1)

array([[0.99505475, 0.99998771, 0.9993293 , 0.99999834],
       [0.9993293 , 0.99505475, 0.99999997, 0.76159416],
       [0.99999997, 0.76159416, 0.76159416, 0.9999092 ]])

In [62]:
np.log10(arr1)

array([[0.47712125, 0.77815125, 0.60205999, 0.84509804],
       [0.60205999, 0.47712125, 0.95424251, 0.        ],
       [0.95424251, 0.        , 0.        , 0.69897   ]])

In [63]:
np.exp(arr1)

array([[2.00855369e+01, 4.03428793e+02, 5.45981500e+01, 1.09663316e+03],
       [5.45981500e+01, 2.00855369e+01, 8.10308393e+03, 2.71828183e+00],
       [8.10308393e+03, 2.71828183e+00, 2.71828183e+00, 1.48413159e+02]])

In [64]:
np.sqrt(arr1)

array([[1.73205081, 2.44948974, 2.        , 2.64575131],
       [2.        , 1.73205081, 3.        , 1.        ],
       [3.        , 1.        , 1.        , 2.23606798]])

In [65]:
np.power(arr1,2)

array([[ 9, 36, 16, 49],
       [16,  9, 81,  1],
       [81,  1,  1, 25]], dtype=int32)

In [66]:
np.mean(arr1)

4.416666666666667

In [67]:
np.median(arr1)

4.0

In [69]:
np.std(arr1)

2.752524094152291

In [70]:
np.var(arr1)

7.576388888888889

In [72]:
np.min(arr1)

1

In [73]:
np.max(arr1)

9